default_platform :ios

platform :ios do
  before_all do
#     setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan
    snapshot
  end

  desc "Internal Testers"
  lane :beta do
    upload_to_testflight(
      ipa:ENV['BITRISE_IPA_PATH'],
      changelog: ENV['GIT_CLONE_COMMIT_MESSAGE_SUBJECT'],
      distribute_external: true,
      app_identifier: "com.nbpapps.DiscontBankApp-Staging",
      groups: [
        "BPs",
      ],
    )
  end

  desc "Submit to review"
  lane :release do 
     upload_to_testflight(
     ipa:ENV['BITRISE_IPA_PATH'],
     changelog: ENV['GIT_CLONE_COMMIT_MESSAGE_SUBJECT'],
     distribute_external: true,
     groups: [
       "BPs",
     ],
     )
     deliver(
       submit_for_review: true,
       force: false,
       automatic_release: false,
       submission_information: {
         add_id_info_uses_idfa: false
       }
     )
 	end
 end