default_platform :ios

platform :ios do
  before_all do
#     setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    scan
    snapshot
  end
  desc "Internal Testers"
  lane :beta do
#     build_app
    upload_to_testflight(
      ipa:ENV['BITRISE_IPA_PATH'],
      changelog: ENV['GIT_CLONE_COMMIT_MESSAGE_SUBJECT'],
      distribute_external: true
    )
  end
 end
