default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
    update_fastlane
  end

  desc "Runs all the tests"
  lane :test do
    scan
#     scan(
#       scheme: "DiscontBankApp",
#       devices: ["iPhone 11"],
#       output_types: "junit",
#       output_directory: "./reports"
#     )
#     snapshot
  end

  desc "Internal Testers for Staging"
  lane :beta do
    upload_to_testflight(
      ipa:ENV['BITRISE_IPA_PATH'],
      changelog: ENV['GIT_CLONE_COMMIT_MESSAGE_SUBJECT'],
      # distribute_external: false
      # reject_build_waiting_for_review: true
      # submit_beta_review: false
      skip_submission: true,
      app_identifier: "com.nbpapps.DiscontBankApp-Staging",
      groups: [
        "BPs",
      ],
    )
  end

  desc "Submit to review"
  lane :release do 
     upload_to_testflight(
     ipa:ENV['BITRISE_IPA_PATH'],
     changelog: ENV['GIT_CLONE_COMMIT_MESSAGE_SUBJECT'],
     distribute_external: true,
     app_identifier: "com.nbpapps.DiscontBankApp",
     reject_build_waiting_for_review: true,
     groups: [
       "BPs",
     ],
     )
     deliver(
       submit_for_review: true,
       force: false,
       app_identifier: "com.nbpapps.DiscontBankApp",
       automatic_release: false,
       submission_information: {
         add_id_info_uses_idfa: false
       }
     )
 	end
 end
