name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build_and_test:
    strategy:
      matrix:
        ios: [14.5]
        device: ["iPhone 12"]

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install iOS Simulator ${{ matrix.ios }}
      if: ${{ matrix.ios != 'latest' }}
      run: xcversion simulators --install='iOS ${{ matrix.ios }}' || true

    - name: Fastlane
      run: |
        fastlane test device:"${{ matrix.device }}" ios:"${{ matrix.ios }}"
      env:
          IFTTT_API_KEY: ${{ secrets.IFTTT_API_KEY }}

#     - name: Publish Report
#       uses: mikepenz/action-junit-report@v3
#       if: always()
#       with:
#         check_name: Test Report
#         report_paths: ./reports/

